site_name: "Ansible Metateam Standards and Best Practices"
site_author: Red Hat Ansible Metateam
docs_dir: docs
#python_module: mkdocs_macros

## Add the pages you want built here
##
#  The hierarchy of the list describes how these pages will be represented in the navigation
#  bar at the top of the page. Either as individual links or as a dropdown menu of links

nav:
- Home: README.md
  - Create a Role: CREATE_A_ROLE.md
  - Retrofit a Role: RETROFIT_A_ROLE.md